import mongoose from "mongoose";

// Form field configuration schema
const fieldConfigSchema = new mongoose.Schema({
    fieldId: {
        type: String,
        required: true,
    },
    label: {
        type: String,
        required: true,
    },
    placeholder: {
        type: String,
        default: "",
    },
    type: {
        type: String,
        enum: ["text", "number", "email", "textarea", "dropdown", "slider", "buttons"],
        default: "text",
    },
    required: {
        type: Boolean,
        default: false,
    },
    visible: {
        type: Boolean,
        default: true,
    },
    gridSpan: {
        type: Number,
        default: 1,
        min: 1,
        max: 3,
    },
    order: {
        type: Number,
        default: 0,
    },
    section: {
        type: String,
        enum: ["company", "transport", "charges"],
        default: "company",
    },
    constraints: {
        maxLength: { type: Number, default: null },
        minLength: { type: Number, default: null },
        min: { type: Number, default: null },
        max: { type: Number, default: null },
        step: { type: Number, default: null },
        pattern: { type: String, default: null },
        patternMessage: { type: String, default: null },
    },
    options: [{
        value: String,
        label: String,
        enabled: { type: Boolean, default: true },
    }],
    inputMode: {
        type: String,
        enum: ["text", "numeric", "email", "tel", null],
        default: null,
    },
    autoCapitalize: {
        type: String,
        enum: ["none", "words", "characters", "uppercase", null],
        default: null,
    },
    suffix: {
        type: String,
        default: null,
    },
});

// Change history entry schema
const changeHistorySchema = new mongoose.Schema({
    timestamp: {
        type: Date,
        default: Date.now,
    },
    userId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "customers",
    },
    userName: {
        type: String,
        default: "",
    },
    action: {
        type: String,
        enum: ["edit", "delete", "restore", "create"],
        required: true,
    },
    fieldId: {
        type: String,
        required: true,
    },
    before: {
        type: mongoose.Schema.Types.Mixed,
        default: {},
    },
    after: {
        type: mongoose.Schema.Types.Mixed,
        default: {},
    },
});

// Main form config schema
const formConfigSchema = new mongoose.Schema(
    {
        pageId: {
            type: String,
            required: true,
            unique: true,
            index: true,
        },
        pageName: {
            type: String,
            required: true,
        },
        description: {
            type: String,
            default: "",
        },
        fields: [fieldConfigSchema],
        changeHistory: [changeHistorySchema],
        lastModifiedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "customers",
        },
        lastModifiedAt: {
            type: Date,
            default: Date.now,
        },
    },
    { timestamps: true }
);

// Default field configs for Add Vendor page
export const DEFAULT_ADD_VENDOR_FIELDS = [
    // ═══════════════════════════════════════════════════════════════════════════
    // SECTION 1: Company & Contact Information
    // ═══════════════════════════════════════════════════════════════════════════
    {
        fieldId: "companyName",
        label: "Company Name",
        placeholder: "Enter company name",
        type: "text",
        required: true,
        visible: true,
        gridSpan: 1,
        order: 1,
        section: "company",
        constraints: { maxLength: 60, minLength: 1 },
    },
    {
        fieldId: "contactPersonName",
        label: "Contact Person",
        placeholder: "Enter contact person name",
        type: "text",
        required: true,
        visible: true,
        gridSpan: 1,
        order: 2,
        section: "company",
        constraints: { maxLength: 30, minLength: 1 },
        autoCapitalize: "uppercase",
    },
    {
        fieldId: "vendorPhoneNumber",
        label: "Phone Number",
        placeholder: "10-digit phone number",
        type: "text",
        required: true,
        visible: true,
        gridSpan: 1,
        order: 3,
        section: "company",
        constraints: { maxLength: 10, minLength: 10 },
        inputMode: "numeric",
    },
    {
        fieldId: "vendorEmailAddress",
        label: "Email Address",
        placeholder: "email@example.com",
        type: "email",
        required: true,
        visible: true,
        gridSpan: 1,
        order: 4,
        section: "company",
        constraints: {},
    },
    {
        fieldId: "gstin",
        label: "GST Number",
        placeholder: "15-character GST number",
        type: "text",
        required: false,
        visible: true,
        gridSpan: 1,
        order: 5,
        section: "company",
        constraints: { maxLength: 15, minLength: 15 },
        autoCapitalize: "uppercase",
    },
    {
        fieldId: "subVendor",
        label: "Sub Transporter",
        placeholder: "Enter sub vendor (optional)",
        type: "text",
        required: false,
        visible: true,
        gridSpan: 1,
        order: 6,
        section: "company",
        constraints: { maxLength: 20 },
        autoCapitalize: "uppercase",
    },
    {
        fieldId: "vendorCode",
        label: "Transporter Code",
        placeholder: "Enter vendor code (optional)",
        type: "text",
        required: false,
        visible: true,
        gridSpan: 1,
        order: 7,
        section: "company",
        constraints: { maxLength: 20 },
        autoCapitalize: "uppercase",
    },
    {
        fieldId: "pincode",
        label: "Pincode",
        placeholder: "6-digit pincode",
        type: "text",
        required: true,
        visible: true,
        gridSpan: 1,
        order: 8,
        section: "company",
        constraints: { maxLength: 6, minLength: 6 },
        inputMode: "numeric",
    },
    {
        fieldId: "address",
        label: "Address",
        placeholder: "Enter complete address",
        type: "textarea",
        required: true,
        visible: true,
        gridSpan: 2,
        order: 9,
        section: "company",
        constraints: { maxLength: 150, minLength: 1 },
    },
    {
        fieldId: "state",
        label: "State",
        placeholder: "State (auto-filled)",
        type: "text",
        required: true,
        visible: true,
        gridSpan: 1,
        order: 10,
        section: "company",
        constraints: {},
    },
    {
        fieldId: "city",
        label: "City",
        placeholder: "City (auto-filled)",
        type: "text",
        required: true,
        visible: true,
        gridSpan: 1,
        order: 11,
        section: "company",
        constraints: {},
    },
    {
        fieldId: "serviceMode",
        label: "Service Modes",
        placeholder: "",
        type: "buttons",
        required: true,
        visible: true,
        gridSpan: 1,
        order: 12,
        section: "company",
        constraints: {},
        options: [
            { value: "FTL", label: "FTL" },
            { value: "LTL", label: "LTL" },
        ],
    },
    {
        fieldId: "companyRating",
        label: "Company Rating",
        placeholder: "",
        type: "slider",
        required: true,
        visible: true,
        gridSpan: 1,
        order: 13,
        section: "company",
        constraints: { min: 1, max: 5, step: 0.1 },
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // SECTION 2: Transport Mode Configuration
    // ═══════════════════════════════════════════════════════════════════════════
    {
        fieldId: "transportMode",
        label: "Transport Mode",
        placeholder: "",
        type: "dropdown",
        required: true,
        visible: true,
        gridSpan: 1,
        order: 14,
        section: "transport",
        constraints: {},
        options: [
            { value: "road", label: "Road", enabled: true },
            { value: "air", label: "Air", enabled: false },
            { value: "rail", label: "Rail", enabled: false },
            { value: "ship", label: "Ship", enabled: false },
        ],
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // SECTION 3: Basic Charges
    // ═══════════════════════════════════════════════════════════════════════════
    {
        fieldId: "docketCharges",
        label: "Docket Charges",
        placeholder: "",
        type: "number",
        required: true,
        visible: true,
        gridSpan: 1,
        order: 17,
        section: "charges",
        constraints: { min: 0, max: 100000 },
        suffix: "₹",
    },
    {
        fieldId: "minWeightKg",
        label: "Min Chargeable Weight",
        placeholder: "",
        type: "number",
        required: false,
        visible: true,
        gridSpan: 1,
        order: 18,
        section: "charges",
        constraints: { min: 0, max: 100000 },
        suffix: "KG",
    },
    {
        fieldId: "minimumCharges",
        label: "Minimum Charges",
        placeholder: "",
        type: "number",
        required: false,
        visible: true,
        gridSpan: 1,
        order: 19,
        section: "charges",
        constraints: { min: 0, max: 100000 },
        suffix: "₹",
    },
    {
        fieldId: "hamaliCharges",
        label: "Hamali Charges",
        placeholder: "",
        type: "number",
        required: false,
        visible: true,
        gridSpan: 1,
        order: 20,
        section: "charges",
        constraints: { min: 0, max: 100000 },
        suffix: "₹",
    },
    {
        fieldId: "greenTax",
        label: "Green Tax / NGT",
        placeholder: "",
        type: "number",
        required: false,
        visible: true,
        gridSpan: 1,
        order: 21,
        section: "charges",
        constraints: { min: 0, max: 100000 },
        suffix: "₹",
    },
    {
        fieldId: "miscCharges",
        label: "MISC / AOC Charges",
        placeholder: "",
        type: "number",
        required: false,
        visible: true,
        gridSpan: 1,
        order: 22,
        section: "charges",
        constraints: { min: 0, max: 100000 },
        suffix: "₹",
    },
    {
        fieldId: "fuelSurchargePct",
        label: "Fuel Surcharge",
        placeholder: "Select or type 0-50",
        type: "number",
        required: true,
        visible: true,
        gridSpan: 1,
        order: 23,
        section: "charges",
        constraints: { min: 0, max: 50 },
        suffix: "%",
    },
    {
        fieldId: "daccCharges",
        label: "DACC Charges",
        placeholder: "",
        type: "number",
        required: false,
        visible: true,
        gridSpan: 1,
        order: 24,
        section: "charges",
        constraints: { min: 0, max: 100000 },
        suffix: "₹",
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // SECTION 4: Handling & Additional Charges
    // ═══════════════════════════════════════════════════════════════════════════
    {
        fieldId: "handlingCharges",
        label: "Handling",
        placeholder: "",
        type: "number",
        required: false,
        visible: true,
        gridSpan: 1,
        order: 25,
        section: "charges",
        constraints: { min: 0, max: 5000 },
        suffix: "₹",
    },
    {
        fieldId: "rovCharges",
        label: "ROV / FOV",
        placeholder: "",
        type: "number",
        required: false,
        visible: true,
        gridSpan: 1,
        order: 26,
        section: "charges",
        constraints: { min: 0, max: 5000 },
        suffix: "₹",
    },
    {
        fieldId: "codCharges",
        label: "COD / DOD",
        placeholder: "",
        type: "number",
        required: false,
        visible: true,
        gridSpan: 1,
        order: 27,
        section: "charges",
        constraints: { min: 0, max: 5000 },
        suffix: "₹",
    },
    {
        fieldId: "toPayCharges",
        label: "To-Pay",
        placeholder: "",
        type: "number",
        required: false,
        visible: true,
        gridSpan: 1,
        order: 28,
        section: "charges",
        constraints: { min: 0, max: 5000 },
        suffix: "₹",
    },
    {
        fieldId: "appointmentCharges",
        label: "Appointment",
        placeholder: "",
        type: "number",
        required: false,
        visible: true,
        gridSpan: 1,
        order: 29,
        section: "charges",
        constraints: { min: 0, max: 5000 },
        suffix: "₹",
    },
];

export default mongoose.model("formConfigs", formConfigSchema);

